### ISSUE TITLE
抓取书籍时出错

### ISSUE THREAD

**Issue by MrZCHZCH** [magicdawn/weread-spy#13]
C:\Users\46266\AppData\Local\pnpm\global\5\.pnpm\puppeteer@15.5.0\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading '$store')
    at pptr://__puppeteer_evaluation_script__:2:34
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\46266\AppData\Local\pnpm\global\5\.pnpm\puppeteer@15.5.0\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\46266\AppData\Local\pnpm\global\5\.pnpm\puppeteer@15.5.0\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async ElementHandle.evaluate (C:\Users\46266\AppData\Local\pnpm\global\5\.pnpm\puppeteer@15.5.0\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:105:16)
    at async ElementHandle.$eval (C:\Users\46266\AppData\Local\pnpm\global\5\.pnpm\puppeteer@15.5.0\node_modules\puppeteer\lib\cjs\puppeteer\common\ElementHandle.js:665:24)
    at async waitCondition (C:\Users\46266\AppData\Local\pnpm\global\5\.pnpm\weread-spy@0.2.0\node_modules\weread-spy\lib\commands\one.js:90:18)
    at async decideDownload (C:\Users\46266\AppData\Local\pnpm\global\5\.pnpm\weread-spy@0.2.0\node_modules\weread-spy\lib\commands\one.js:98:5)

**Comment by karpoul** [comment]
怎么解决的？
