### ISSUE TITLE
TypeError: Cannot read properties of null (reading '$store')

### ISSUE THREAD

**Issue by deckvig** [magicdawn/weread-spy#20]
weread-spy 0.3.0 和 0.4.0 都报如下错误。尝试过升级 puppeteer-core 到最新版本，仍有这个问题

Error: Evaluation failed: TypeError: Cannot read properties of null (reading '$store')
    at pptr://__puppeteer_evaluation_script__:2:34
    at ExecutionContext._ExecutionContext_evaluate (/private/tmp/test/weread-spy/node_modules/.pnpm/puppeteer-core@19.7.5_typescript@4.9.5/node_modules/puppeteer-core/src/common/ExecutionContext.ts:319:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/private/tmp/test/weread-spy/node_modules/.pnpm/puppeteer-core@19.7.5_typescript@4.9.5/node_modules/puppeteer-core/src/common/ExecutionContext.ts:181:12)
    at async CDPJSHandle.evaluate (/private/tmp/test/weread-spy/node_modules/.pnpm/puppeteer-core@19.7.5_typescript@4.9.5/node_modules/puppeteer-core/src/common/JSHandle.ts:74:12)
    at async CDPElementHandle.$eval (/private/tmp/test/weread-spy/node_modules/.pnpm/puppeteer-core@19.7.5_typescript@4.9.5/node_modules/puppeteer-core/src/common/ElementHandle.ts:145:20)
    at async waitCondition (/private/tmp/test/weread-spy/src/commands/one.ts:102:12)
    at async decideDownload (/private/tmp/test/weread-spy/src/commands/one.ts:111:3)

**Comment by deckvig** [comment]
这个 Case 比较奇怪，相同的书籍，我间隔几天再执行任务的时候又能正常运行
