### ISSUE TITLE
Internal Error: Failed to launch the browser process

### ISSUE THREAD

**Issue by whitewatercn** [magicdawn/weread-spy#23]
运行`weread-spy`时报错，提示无法打开浏览器，应该是puppeteer的问题，但不知道怎么处理

通过pnpm安装
pnpm v8.4.0
npm v9.5.1
nodejs v18.16.0
Windows10

错误代码
```
Internal Error: Failed to launch the browser process! undefined
[16308:12068:0508/024016.443:FATAL:chrome_resource_bundle_helper.cc(107)] Check failed: !actual_locale.empty(). Locale could not be found for
Backtrace:
        IsSandboxedProcess [0x00007FFCC20A1062+998194]
        IsSandboxedProcess [0x00007FFCC2E38402+15249106]
        IsSandboxedProcess [0x00007FFCC21311D2+1588386]
        IsSandboxedProcess [0x00007FFCC2132250+1592608]
        IsSandboxedProcess [0x00007FFCC20469A8+627832]
        ChromeMain [0x00007FFCBE7F1E95+3573]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FFCC19FCAC2+24761666]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FFCC19FC764+24760804]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FFCC19FAF5F+24754655]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FFCC19FB21E+24755358]
        ChromeMain [0x00007FFCBE7F133F+671]
        GetPakFileHashes [0x00007FF722EB29FF+6655]
        GetPakFileHashes [0x00007FF722EB1A96+2710]
        GetHandleVerifier [0x00007FF7230235B2+1030434]
        BaseThreadInitThunk [0x00007FFD5E787604+20]
        RtlUserThreadStart [0x00007FFD5F9426A1+33]
Crash keys:
  "reentry_guard_tls_slot" = "unused"
  "variations" = "db59f83a-3f4a17df,8bccc03b-3f4a17df,fabf21f1-3f4a17df,272b4158-3f4a17df,2510663e-73703436,"
  "num-experiments" = "5"
  "switch-27" = "about:blank"
  "switch-26" = "--remote-debugging-port=0"
  "switch-25" = "--user-data-dir=C:\Users\white\AppData\Local\weread-spy\Data\ppt"
  "switch-24" = "--use-mock-keychain"
  "switch-23" = "--password-store=basic"
  "switch-22" = "--no-first-run"
  "switch-21" = "--metrics-recording-only"
  "switch-20" = "--force-color-profile=srgb"
  "switch-19" = "--export-tagged-pdf"
  "switch-18" = "--enable-blink-features=IdleDetection"
  "switch-17" = "--disable-sync"
  "switch-16" = "--disable-renderer-backgrounding"
  "switch-15" = "--disable-prompt-on-repost"
  "switch-14" = "--disable-popup-blocking"
  "switch-13" = "--disable-ipc-flooding-protection"
  "switch-12" = "--disable-hang-monitor"
  "switch-11" = "--disable-extensions"
  "switch-10" = "--disable-dev-shm-usage"
  "switch-9" = "--disable-default-apps"
  "switch-8" = "--disable-component-update"
  "switch-7" = "--disable-component-extensions-with-background-pages"
  "switch-6" = "--disable-client-side-phishing-detection"
  "switch-5" = "--disable-breakpad"
  "switch-4" = "--disable-backgrounding-occluded-windows"
  "switch-3" = "--disable-background-timer-throttling"
  "switch-2" = "--disable-background-networking"
  "switch-1" = "--allow-pre-commit-input"
  "num-switches" = "29"
  "commandline-disabled-feature-5" = "OptimizationHints"
  "commandline-disabled-feature-4" = "MediaRouter"
  "commandline-disabled-feature-3" = "AcceptCHFrame"
  "commandline-disabled-feature-2" = "BackForwardCache"
  "commandline-disabled-feature-1" = "Translate"
  "commandline-enabled-feature-1" = "NetworkServiceInProcess2"



TROUBLESHOOTING: https://pptr.dev/troubleshooting

[16308:12068:0508/024016.443:FATAL:chrome_resource_bundle_helper.cc(107)] Check failed: !actual_locale.empty(). Locale could not be found for
Backtrace:
        IsSandboxedProcess [0x00007FFCC20A1062+998194]
        IsSandboxedProcess [0x00007FFCC2E38402+15249106]
        IsSandboxedProcess [0x00007FFCC21311D2+1588386]
        IsSandboxedProcess [0x00007FFCC2132250+1592608]
        IsSandboxedProcess [0x00007FFCC20469A8+627832]
        ChromeMain [0x00007FFCBE7F1E95+3573]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FFCC19FCAC2+24761666]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FFCC19FC764+24760804]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FFCC19FAF5F+24754655]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FFCC19FB21E+24755358]
        ChromeMain [0x00007FFCBE7F133F+671]
        GetPakFileHashes [0x00007FF722EB29FF+6655]
        GetPakFileHashes [0x00007FF722EB1A96+2710]
        GetHandleVerifier [0x00007FF7230235B2+1030434]
        BaseThreadInitThunk [0x00007FFD5E787604+20]
        RtlUserThreadStart [0x00007FFD5F9426A1+33]
Crash keys:
  "reentry_guard_tls_slot" = "unused"
  "variations" = "db59f83a-3f4a17df,8bccc03b-3f4a17df,fabf21f1-3f4a17df,272b4158-3f4a17df,2510663e-73703436,"
  "num-experiments" = "5"
  "switch-27" = "about:blank"
  "switch-26" = "--remote-debugging-port=0"
  "switch-25" = "--user-data-dir=C:\Users\white\AppData\Local\weread-spy\Data\ppt"
  "switch-24" = "--use-mock-keychain"
  "switch-23" = "--password-store=basic"
  "switch-22" = "--no-first-run"
  "switch-21" = "--metrics-recording-only"
  "switch-20" = "--force-color-profile=srgb"
  "switch-19" = "--export-tagged-pdf"
  "switch-18" = "--enable-blink-features=IdleDetection"
  "switch-17" = "--disable-sync"
  "switch-16" = "--disable-renderer-backgrounding"
  "switch-15" = "--disable-prompt-on-repost"
  "switch-14" = "--disable-popup-blocking"
  "switch-13" = "--disable-ipc-flooding-protection"
  "switch-12" = "--disable-hang-monitor"
  "switch-11" = "--disable-extensions"
  "switch-10" = "--disable-dev-shm-usage"
  "switch-9" = "--disable-default-apps"
  "switch-8" = "--disable-component-update"
  "switch-7" = "--disable-component-extensions-with-background-pages"
  "switch-6" = "--disable-client-side-phishing-detection"
  "switch-5" = "--disable-breakpad"
  "switch-4" = "--disable-backgrounding-occluded-windows"
  "switch-3" = "--disable-background-timer-throttling"
  "switch-2" = "--disable-background-networking"
  "switch-1" = "--allow-pre-commit-input"
  "num-switches" = "29"
  "commandline-disabled-feature-5" = "OptimizationHints"
  "commandline-disabled-feature-4" = "MediaRouter"
  "commandline-disabled-feature-3" = "AcceptCHFrame"
  "commandline-disabled-feature-2" = "BackForwardCache"
  "commandline-disabled-feature-1" = "Translate"
  "commandline-enabled-feature-1" = "NetworkServiceInProcess2"



TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (C:\Users\white\AppData\Local\pnpm\global\5\.pnpm\registry.npmmirror.com+@puppeteer+browsers@0.5.0\node_modules\@puppeteer\browsers\lib\cjs\launch.js:262:24)
    at ChildProcess.emit (node:events:525:35)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by whitewatercn** [comment]
解决了，参考
> Same after update to puppeteer@3.0.0 @jackfranklin
> 
> Platform: Github Actions, Ubuntu 18.04 Node version: 10.x
> 
> **What steps will reproduce the problem?**
> 
> ```
> git clone https://github.com/mrdoob/three.js
> npm un puppeteer && npm i -D puppeteer@3.0.0
> npm install
> npm run test-e2e webgl_animation_keyframes
> ```
> 
> **What happens instead?**
> 
> ```
> TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
> 
>     at onClose (/home/runner/work/three.js/three.js/node_modules/puppeteer/lib/Launcher.js:615:20)
>     at Interface.helper.addEventListener (/home/runner/work/three.js/three.js/node_modules/puppeteer/lib/Launcher.js:605:56)
>     at Interface.emit (events.js:203:15)
>     at Interface.close (readline.js:397:8)
>     at Socket.onend (readline.js:173:10)
>     at Socket.emit (events.js:203:15)
>     at endReadableNT (_stream_readable.js:1145:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> (node:2839) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:2839) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

我也是病急乱投医，分别执行了
```
npm un puppeteer 
npm i -D puppeteer
npm install
```
不是很懂这些参数的意义，但解决问题了，期待大佬解释一下发生了什么
